# Generated by Django 2.0.7 on 2018-08-04 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid
import wakfustrat.wiki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(verbose_name='contenu au format MarkDown')),
                ('html', models.TextField(verbose_name='contenu au format HTML')),
                ('toc', models.TextField(verbose_name='table des matières')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('version', models.PositiveIntegerField(editable=False, verbose_name='version')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('diff_count', models.IntegerField(default=0, verbose_name='quantité modifiée')),
                ('object_id', models.PositiveIntegerField()),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='par')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('status', model_utils.fields.StatusField(choices=[('empty', 'Vide'), ('draft', 'Brouillon'), ('published', 'Terminé')], default='empty', max_length=100, no_check_for_status=True)),
                ('boss', models.CharField(max_length=64, verbose_name='boss')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='niveau')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(0, 'Très facile'), (1, 'Facile'), (2, 'Normal'), (3, 'Difficile'), (4, 'Très difficile')], help_text="Il s'agit d'une indication subjective à propos de la complexité de la stratégie du donjon", verbose_name='difficulté')),
                ('image', models.ImageField(blank=True, null=True, upload_to=wakfustrat.wiki.models.upload_dungeon_image, verbose_name='image')),
                ('subzone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.SubZone', verbose_name='sous-zone')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Zone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'Donjon',
                'verbose_name_plural': 'Donjons',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=wakfustrat.wiki.models.upload_to_image, verbose_name='image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
