# Generated by Django 2.0.7 on 2018-08-11 12:12

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
    ]
