# Generated by Django 2.0.7 on 2018-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180811_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='boss',
            name='images',
            field=models.ManyToManyField(blank=True, to='wiki.Image', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='images',
            field=models.ManyToManyField(blank=True, to='wiki.Image', verbose_name='Images'),
        ),
    ]
