# Generated by Django 2.0.7 on 2018-08-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wiki', '0004_auto_20180815_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Page mise en avant',
                'verbose_name_plural': 'Pages mise en avant',
            },
        ),
    ]
