# Generated by Django 2.0.7 on 2018-08-15 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_featuredpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'Brouillon'), ('published', 'Terminé')], default='draft', max_length=100, no_check_for_status=True)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'Quête',
                'verbose_name_plural': 'Quêtes',
            },
        ),
        migrations.CreateModel(
            name='QuestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.QuestCategory'),
        ),
        migrations.AddField(
            model_name='quest',
            name='images',
            field=models.ManyToManyField(blank=True, to='wiki.Image', verbose_name='Images'),
        ),
    ]
