# Generated by Django 2.0.7 on 2018-08-18 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20180815_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questcategory',
            options={'verbose_name': 'Catégorie de quête', 'verbose_name_plural': 'Catégories de quêtes'},
        ),
        migrations.AlterField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.QuestCategory', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='level',
            field=models.PositiveSmallIntegerField(help_text='Niveau minimum pour lancer la quête', validators=[django.core.validators.MaxValueValidator(200)], verbose_name='niveau'),
        ),
    ]
