# Generated by Django 2.0.7 on 2018-08-11 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_user_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='jeton')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date et heure')),
                ('is_used', models.BooleanField(default=False, verbose_name='utilisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Jeton de réinitialisation de mot de passe',
                'verbose_name_plural': 'Jetons de réinitialisation de mot de passe',
            },
        ),
    ]
