# Generated by Django 2.0.7 on 2018-08-18 11:17

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_passwordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Obligatoire. 32 caractères max. Lettres, chiffres et @/./+/-/_ seulement.', max_length=32, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='pseudo'),
        ),
    ]
