# Generated by Django 2.0.7 on 2018-08-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'sous-zone',
                'verbose_name_plural': 'sous-zones',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
            },
        ),
    ]
