# Generated by Django 2.0.7 on 2018-08-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subzone',
            options={'ordering': ('slug',), 'verbose_name': 'sous-zone', 'verbose_name_plural': 'sous-zones'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('slug',), 'verbose_name': 'zone', 'verbose_name_plural': 'zones'},
        ),
    ]
